### ISSUE TITLE
Review help-guide.ipnyb

### ISSUE THREAD

**Issue by fazepher** [warwickdatascience/spotify-workshop#1]
# Part One

## Running Code
- "If you want to step" into "stop". 

## Variables cell
- I think you meant `print(rpm)` instead of `print(x)`. 
Variable Types cell 
- "they mean the seem" into "same".
- Maybe the code should be 
   1. `greeting = 'Hello'` 
   2. `print(greeting)`
   3. `greeting = "Hello"`
   4. `print(greeting)`
   5.  `greeting = Hello`

## Functions cell
- Could be obvious to most people, but some may ask what's the ìmport numpy as np` command.

## For Loops
- Always worth reminding people that range doesn't include the sop argument.

## The Spotify API
- "The Spotiy API" into "Spotify".
- Within Spotipy, "Instead,n" into "Instead".

# Part Two

## Feature Engineering
- "even though the" into "even though they"

## Standardisation
- Maybe verbally explain how do we center and divide? 

## Dimensionality Reduction
- I'm assuming `fit_transform` is used on the breakout session. as you refer to it with "as before".

**Comment by THargreaves** [comment]
These are great suggestions. Thank you. Will integrate them soon.
